### ISSUE TITLE
Android HW 2 "Grid Image Search" completed. [Android Bootcamp]

### ISSUE THREAD

**Issue by asweigart** [asweigart/codepath_hw2_gridsearch#1]
Homework completed. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Nice work. Few notes after checking the code:
- One thing to consider is rather than sending and returning all the filter values separately as keys, might have introduced a serializable model (i.e `SearchFilters.java`) representing all the filters which were passed back and forth between activities within the bundle.
- Correctly used `Parcelable` instead of `Serializable` 
- Nice work setting up shared preferences to persist the settings between activities
- Properly used spinners (with populated values) to allow users to select filters
- Nice effort on improving the UI/UX and also implementing modal overlay for filters
- Nice job adding the share intent to the image detail view!
- Nice to see you added the search box to the ActionBar!
- You're assuming in `onFailure` that internet is not present, which is incorrect. Please consider doing it [correctly](https://guides.codepath.com/android/Sending-and-Managing-Network-Requests)
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out in addition to the placeholder images.

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
